name: validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate-all:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - uses: azure/setup-helm@v4
        with:
          version: v3.16.2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - run: make validate-all
